name: Deploy Yii2 to Azure App Service

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: asistencia-api-itvh
  RESOURCE_GROUP: asistencia-app
  PHP_VERSION: '8.2'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: intl, gd, pdo_mysql, zip
        tools: composer

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-dev --optimize-autoloader
        composer dump-autoload --optimize

    - name: Configure Yii2 for production
      run: |
        # Configuración de producción en index.php
        cat << 'EOF' > web/index.php
        <?php
        defined('YII_DEBUG') or define('YII_DEBUG', false);
        defined('YII_ENV') or define('YII_ENV', 'prod');
        
        require __DIR__ . '/../vendor/autoload.php';
        require __DIR__ . '/../vendor/yiisoft/yii2/Yii.php';
        
        $config = require __DIR__ . '/../config/web.php';
        
        (new yii\web\Application($config))->run();
        EOF

        # Configuración de assetManager
        sed -i "/'components' => \[/a \
        'assetManager' => [\n\
            'basePath' => '@webroot/assets',\n\
            'baseUrl' => '@web/assets',\n\
        ]," config/web.php

        # Crear directorios necesarios
        mkdir -p web/assets
        chmod -R 755 web/assets
        chmod -R 755 runtime

    - name: Create optimized startup script
      run: |
        cat << 'EOF' > startup.sh
        #!/bin/bash

        # =============================================
        # CONFIGURACIÓN OPTIMIZADA PARA AZURE
        # =============================================

        # 1. Configurar PHP-FPM
        echo "Configurando PHP-FPM..."
        cat > /usr/local/etc/php-fpm.d/zz-azure.conf << 'EOL'
        [www]
        user = www-data
        group = www-data
        listen = /tmp/php-fpm.sock
        listen.owner = www-data
        listen.group = www-data
        listen.mode = 0660
        pm = dynamic
        pm.max_children = 10
        pm.start_servers = 2
        pm.min_spare_servers = 1
        pm.max_spare_servers = 3
        EOL

        # 2. Configurar Nginx correctamente para Yii2
        echo "Configurando Nginx..."
        cat > /etc/nginx/conf.d/default.conf << 'EOL'
        server {
            listen 8080;
            server_name localhost;
            root /home/site/wwwroot/web;
            index index.php;

            # Configuración de seguridad
            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-XSS-Protection "1; mode=block";
            add_header X-Content-Type-Options "nosniff";

            location / {
                try_files \$uri \$uri/ /index.php?\$args;
            }

            location ~ \.php$ {
                fastcgi_pass unix:/tmp/php-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
                include fastcgi_params;
            }

            location ~ /\.(ht|svn|git) {
                deny all;
            }
        }
        EOL

        # 3. Iniciar servicios
        echo "Iniciando PHP-FPM..."
        php-fpm -D

        echo "Iniciando Nginx..."
        exec nginx -g "daemon off;"
        EOF

        chmod +x startup.sh

    - name: Zip artifact
      run: zip -r release.zip . -x '*.git*'

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Configure Azure App Service
      uses: azure/cli@v1
      with:
        inlineScript: |
          az webapp config set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --linux-fx-version "PHP|${{ env.PHP_VERSION }}" \
            --startup-file "startup.sh"

          az webapp config appsettings set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --settings \
              WEBSITES_ENABLE_APP_SERVICE_STORAGE=true \
              WEBSITES_PORT=8080 \
              PHP_FPM_MAX_CHILDREN=10 \
              PHP_FPM_START_SERVERS=2 \
              PHP_FPM_MIN_SPARE_SERVERS=1 \
              PHP_FPM_MAX_SPARE_SERVERS=3 \
              YII_ENV=prod

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: release.zip
